# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI/nueva_tecla.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog_Nueva_Tecla(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(628, 77)

        self.aceptar_cancelar = QtWidgets.QDialogButtonBox(Dialog)
        self.aceptar_cancelar.setGeometry(QtCore.QRect(540, 10, 81, 61))
        self.aceptar_cancelar.setOrientation(QtCore.Qt.Vertical)
        self.aceptar_cancelar.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel | QtWidgets.QDialogButtonBox.Ok)
        self.aceptar_cancelar.setObjectName("aceptar_cancelar")

        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(10, 10, 91, 17))
        self.label.setObjectName("label")

        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(10, 40, 67, 17))
        self.label_2.setObjectName("label_2")

        self.tecla_input = QtWidgets.QLineEdit(Dialog)
        self.tecla_input.setGeometry(QtCore.QRect(110, 10, 31, 25))
        self.tecla_input.setObjectName("tecla")

        self.roca_input = QtWidgets.QLineEdit(Dialog)
        self.roca_input.setGeometry(QtCore.QRect(60, 40, 461, 25))
        self.roca_input.setObjectName("roca")

        self.retranslateUi(Dialog)
        self.aceptar_cancelar.accepted.connect(Dialog.accept)  # type: ignore
        self.aceptar_cancelar.rejected.connect(Dialog.reject)  # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Nueva tecla"))
        self.label.setText(_translate("Dialog", "Nueva tecla:"))
        self.label_2.setText(_translate("Dialog", "Roca:"))
