# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI/sesion.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1078, 797)

        self.aceptar_cancelar = QtWidgets.QDialogButtonBox(Dialog)
        self.aceptar_cancelar.setGeometry(QtCore.QRect(380, 760, 171, 32))
        self.aceptar_cancelar.setOrientation(QtCore.Qt.Horizontal)
        self.aceptar_cancelar.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.aceptar_cancelar.setObjectName("aceptar_cancelar")

        self.deshacerButton = QtWidgets.QCommandLinkButton(Dialog)
        self.deshacerButton.setGeometry(QtCore.QRect(190, 760, 191, 31))
        self.deshacerButton.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.deshacerButton.setObjectName("deshacerButton")

        self.scrollRocas = QtWidgets.QScrollArea(Dialog)
        self.scrollRocas.setGeometry(QtCore.QRect(0, 0, 551, 751))
        self.scrollRocas.setWidgetResizable(True)
        self.scrollRocas.setObjectName("scrollRocas")

        self.scrollRocasWidgetContents = QtWidgets.QWidget()
        self.scrollRocasWidgetContents.setGeometry(QtCore.QRect(0, 0, 549, 749))
        self.scrollRocasWidgetContents.setObjectName("scrollRocasWidgetContents")
        self.scrollRocas.setWidget(self.scrollRocasWidgetContents)

        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(10, 760, 41, 17))
        self.label.setObjectName("label")

        self.input = QtWidgets.QLineEdit(Dialog)
        self.input.setGeometry(QtCore.QRect(60, 760, 121, 25))
        self.input.setObjectName("input")

        self.editarMapaBoton = QtWidgets.QPushButton(Dialog)
        self.editarMapaBoton.setGeometry(QtCore.QRect(560, 760, 511, 31))
        self.editarMapaBoton.setObjectName("editarMapaBoton")

        self.scrollMapa = QtWidgets.QScrollArea(Dialog)
        self.scrollMapa.setGeometry(QtCore.QRect(560, 0, 511, 751))
        self.scrollMapa.setWidgetResizable(True)
        self.scrollMapa.setObjectName("scrollMapa")

        self.scrollMapaWidgetContents = QtWidgets.QWidget()
        self.scrollMapaWidgetContents.setGeometry(QtCore.QRect(0, 0, 509, 749))
        self.scrollMapaWidgetContents.setObjectName("scrollMapaWidgetContents")

        self.label_tecla_1 = QtWidgets.QLabel(self.scrollMapaWidgetContents)
        self.label_tecla_1.setGeometry(QtCore.QRect(0, 0, 67, 17))
        self.label_tecla_1.setObjectName("label_tecla_1")
        self.label_tecla_1.setText("TextLabel")

        self.label_tecla_2 = QtWidgets.QLabel(self.scrollMapaWidgetContents)
        self.label_tecla_2.setGeometry(QtCore.QRect(0, 20, 67, 17))
        self.label_tecla_2.setObjectName("label_tecla_2")
        self.scrollMapa.setWidget(self.scrollMapaWidgetContents)
        self.label_tecla_2.setText("TextLabel")

        self.retranslateUi(Dialog)
        self.aceptar_cancelar.accepted.connect(Dialog.accept) # type: ignore
        self.aceptar_cancelar.rejected.connect(Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.deshacerButton.setText(_translate("Dialog", "Deshacer"))
        self.label.setText(_translate("Dialog", "Input"))
        self.editarMapaBoton.setText(_translate("Dialog", "Editar mapa de teclas"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
