# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'nueva_muestra.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtWidgets


class Ui_NuevaMuestraWindow(object):
    def setupUi(self, NuevaMuestraWindow):
        NuevaMuestraWindow.setObjectName("NuevaMuestraWindow")
        NuevaMuestraWindow.resize(430, 470)
        self.centralwidget = QtWidgets.QWidget(NuevaMuestraWindow)
        self.centralwidget.setObjectName("centralwidget")

        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 10, 161, 17))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 60, 161, 17))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(10, 110, 161, 17))
        self.label_3.setObjectName("label_3")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(10, 160, 161, 17))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(10, 210, 161, 17))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(10, 260, 161, 17))
        self.label_7.setObjectName("label_7")

        self.nombre = QtWidgets.QLineEdit(self.centralwidget)
        self.nombre.setGeometry(QtCore.QRect(10, 30, 411, 25))
        self.nombre.setObjectName("nombre")
        self.fecha = QtWidgets.QDateEdit(self.centralwidget)
        self.fecha.setGeometry(QtCore.QRect(10, 80, 110, 26))
        self.fecha.setCalendarPopup(True)
        self.fecha.setObjectName("fecha")
        self.localidad = QtWidgets.QLineEdit(self.centralwidget)
        self.localidad.setGeometry(QtCore.QRect(10, 130, 411, 25))
        self.localidad.setObjectName("localidad")
        self.operador = QtWidgets.QLineEdit(self.centralwidget)
        self.operador.setGeometry(QtCore.QRect(10, 180, 411, 25))
        self.operador.setObjectName("operador")
        self.cantidad_lecturas = QtWidgets.QSpinBox(self.centralwidget)
        self.cantidad_lecturas.setGeometry(QtCore.QRect(10, 230, 71, 26))
        self.cantidad_lecturas.setMinimum(0)
        self.cantidad_lecturas.setMaximum(1000)
        self.cantidad_lecturas.setObjectName("cantidad_lecturas")
        self.observaciones = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.observaciones.setGeometry(QtCore.QRect(10, 280, 411, 90))
        self.observaciones.setObjectName("observaciones")

        self.cargar_mapa_boton = QtWidgets.QPushButton(self.centralwidget)
        self.cargar_mapa_boton.setGeometry(QtCore.QRect(10, 390, 221, 25))
        self.cargar_mapa_boton.setObjectName("cargar_mapa_boton")

        self.nuevo_mapa_boton = QtWidgets.QPushButton(self.centralwidget)
        self.nuevo_mapa_boton.setGeometry(QtCore.QRect(10, 420, 221, 25))
        self.nuevo_mapa_boton.setObjectName("nuevo_mapa_boton")

        self.cancelar_aceptar_boton = QtWidgets.QDialogButtonBox(self.centralwidget)
        self.cancelar_aceptar_boton.setGeometry(QtCore.QRect(250, 420, 175, 25))
        self.cancelar_aceptar_boton.setStandardButtons(
            QtWidgets.QDialogButtonBox.Cancel | QtWidgets.QDialogButtonBox.Save)
        self.cancelar_aceptar_boton.setObjectName("cancelar_aceptar_boton")

        NuevaMuestraWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(NuevaMuestraWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 429, 22))
        self.menubar.setObjectName("menubar")
        NuevaMuestraWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(NuevaMuestraWindow)
        self.statusbar.setObjectName("statusbar")
        NuevaMuestraWindow.setStatusBar(self.statusbar)

        self.retranslateUi(NuevaMuestraWindow)
        QtCore.QMetaObject.connectSlotsByName(NuevaMuestraWindow)

    def retranslateUi(self, NuevaMuestraWindow):
        _translate = QtCore.QCoreApplication.translate
        NuevaMuestraWindow.setWindowTitle(_translate("NuevaMuestraWindow", "Nueva muestra"))
        self.label.setText(_translate("NuevaMuestraWindow", "Nombre de la muestra"))
        self.label_2.setText(_translate("NuevaMuestraWindow", "Fecha"))
        self.label_3.setText(_translate("NuevaMuestraWindow", "Localidad"))
        self.label_5.setText(_translate("NuevaMuestraWindow", "Operador"))
        self.label_6.setText(_translate("NuevaMuestraWindow", "Cantidad de lecturas"))
        self.label_7.setText(_translate("NuevaMuestraWindow", "Observaciones"))
        self.nuevo_mapa_boton.setText(_translate("NuevaMuestraWindow", "Crear nuevo mapa de teclas"))
        self.cargar_mapa_boton.setText(_translate("NuevaMuestraWindow", "Cargar mapa de teclas"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    NuevaMuestraWindow = QtWidgets.QMainWindow()
    ui = Ui_NuevaMuestraWindow()
    ui.setupUi(NuevaMuestraWindow)
    NuevaMuestraWindow.show()
    sys.exit(app.exec_())
